name: CI
on:
  pull_request: {}
  push:
    branches: [main]
    paths: ["**.bs"]
jobs:
  main:
    name: Build, Validate and Deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: w3c/spec-prod@v2
        with:
          TOOLCHAIN: bikeshed
          DESTINATION: index.html
          SOURCE: index.bs
          GH_PAGES_BRANCH: gh-pages
          BUILD_FAIL_ON: warning
